# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 9, 13, 1, 16, 515059, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
